/**
 * Install-script generator for Sprint I-α sub-slice 3.
 *
 * Central renders a platform-neutral POSIX shell script that:
 *   1. Detects the target's platform (uname -sm).
 *   2. Downloads the matching llamactl-agent binary from central's
 *      /artifacts endpoint (landed in sub-slice 4).
 *   3. Runs `llamactl-agent agent init --json --host=$RESOLVED_HOST`
 *      and captures stdout to get the bootstrap blob.
 *   4. POSTs `{ bootstrapToken, blob, nodeName }` to central's
 *      /register endpoint (sub-slice 2).
 *   5. Prints success + a pointer at the service setup step
 *      (launchd/systemd templates, sub-slice 5).
 *
 * Tests exercise `generateInstallScript` as a pure function; the
 * handler wires it to a live Bun.serve route that looks up the
 * token for context + renders the script.
 */

import {
  findBootstrapTokenByPlaintext,
  type BootstrapToken,
} from '../config/bootstrap-tokens.js';

export interface GenerateInstallScriptOptions {
  /** Plaintext bootstrap token. Embedded in the script verbatim; the
   *  target host POSTs it to /register. */
  token: string;
  /** URL the target host reaches central at — same value the token
   *  record stores. Trailing slash tolerated. */
  centralUrl: string;
  /** kubeconfig name for the new node. */
  nodeName: string;
}

function sanitizeSingleLine(value: string): string {
  // All values land inside single-quoted shell strings. Reject any
  // embedded single quote early rather than producing malformed
  // shell. Every legitimate token/URL/name is alphanumeric + a small
  // symbol set, so this is a safe policy not an arbitrary one.
  if (value.includes("'")) {
    throw new Error('install-script value may not contain single quotes');
  }
  if (/[\n\r]/.test(value)) {
    throw new Error('install-script value may not contain newlines');
  }
  return value;
}

export function generateInstallScript(opts: GenerateInstallScriptOptions): string {
  const token = sanitizeSingleLine(opts.token);
  const centralUrl = sanitizeSingleLine(opts.centralUrl.replace(/\/$/, ''));
  const nodeName = sanitizeSingleLine(opts.nodeName);
  return `#!/bin/sh
# llamactl install-agent — generated by central for node '${nodeName}'.
# Pipe to sh on the target host:
#   curl -fsSL '${centralUrl}/install-agent.sh?token=<t>' | sh
set -eu

TOKEN='${token}'
CENTRAL_URL='${centralUrl}'
NODE_NAME='${nodeName}'

INSTALL_DIR="\${LLAMACTL_INSTALL_DIR:-\$HOME/.llamactl}"
mkdir -p "$INSTALL_DIR/bin"

# Resolve a sensible --host SAN for the self-signed cert.
RESOLVED_HOST="\${LLAMACTL_AGENT_HOST:-\$(hostname)}"
if [ -z "$RESOLVED_HOST" ]; then RESOLVED_HOST="127.0.0.1"; fi

case "$(uname -sm)" in
  "Darwin arm64") PLATFORM="darwin-arm64" ;;
  "Darwin x86_64") PLATFORM="darwin-x64" ;;
  "Linux x86_64") PLATFORM="linux-x64" ;;
  "Linux aarch64") PLATFORM="linux-arm64" ;;
  *) echo "llamactl install-agent: unsupported platform: $(uname -sm)" >&2; exit 1 ;;
esac

AGENT_BIN="$INSTALL_DIR/bin/llamactl-agent"
echo "llamactl install-agent: downloading agent binary to $AGENT_BIN"
curl -fsSL "$CENTRAL_URL/artifacts/agent/$PLATFORM" -o "$AGENT_BIN"
chmod +x "$AGENT_BIN"

echo "llamactl install-agent: initializing agent config"
INIT_JSON=$("$AGENT_BIN" agent init --dir="$INSTALL_DIR" --name="$NODE_NAME" --host="$RESOLVED_HOST" --json)

# Extract the blob field from the single-line JSON without jq.
BLOB=$(printf '%s' "$INIT_JSON" | sed -n 's/.*"blob":"\\([^"]*\\)".*/\\1/p')
if [ -z "$BLOB" ]; then
  echo "llamactl install-agent: agent init did not emit a bootstrap blob" >&2
  exit 1
fi

echo "llamactl install-agent: registering with $CENTRAL_URL"
REGISTER_STATUS=$(curl -fsS -o "$INSTALL_DIR/register-response.json" -w '%{http_code}' \\
  -X POST "$CENTRAL_URL/register" \\
  -H 'content-type: application/json' \\
  --data "{\\"bootstrapToken\\":\\"$TOKEN\\",\\"nodeName\\":\\"$NODE_NAME\\",\\"blob\\":\\"$BLOB\\"}" || echo "000")

if [ "$REGISTER_STATUS" != "200" ]; then
  echo "llamactl install-agent: /register returned HTTP $REGISTER_STATUS" >&2
  cat "$INSTALL_DIR/register-response.json" >&2 || true
  exit 1
fi

echo "llamactl install-agent: $NODE_NAME registered."
echo ""
echo "Next: set up a launchd plist (macOS) or systemd user unit (Linux) to"
echo "run \\\`$AGENT_BIN agent serve --dir=$INSTALL_DIR\\\` at boot. Templates"
echo "will be generated by a future sub-slice."
`;
}

export interface InstallScriptHandlerOptions {
  bootstrapTokensDir?: string;
}

export async function handleInstallScript(
  req: Request,
  opts: InstallScriptHandlerOptions = {},
): Promise<Response> {
  if (req.method !== 'GET') {
    return new Response('method not allowed', { status: 405 });
  }
  const url = new URL(req.url);
  const token = url.searchParams.get('token');
  if (!token) {
    return new Response(
      '# llamactl install-agent: ?token=<t> query param required\nexit 1\n',
      { status: 400, headers: { 'content-type': 'text/x-shellscript' } },
    );
  }
  const found = findBootstrapTokenByPlaintext(
    token,
    opts.bootstrapTokensDir,
  );
  if (!found) {
    return new Response(
      '# llamactl install-agent: unknown or unknown-format token\nexit 1\n',
      { status: 401, headers: { 'content-type': 'text/x-shellscript' } },
    );
  }
  // We DO NOT validate expiry / used state here — /register is where
  // that lives. If the operator scripts the install over a long
  // duration the script body is still good to inspect; the actual
  // /register POST will reject an exhausted token.
  return renderResponse(found.record, token);
}

function renderResponse(record: BootstrapToken, token: string): Response {
  const body = generateInstallScript({
    token,
    centralUrl: record.centralUrl,
    nodeName: record.nodeName,
  });
  return new Response(body, {
    status: 200,
    headers: {
      'content-type': 'text/x-shellscript',
      // Conservative cache headers — the script embeds secrets.
      'cache-control': 'no-store',
    },
  });
}

